version: '3.5'

services:
  client:
    image: node:latest
    volumes:
      - ./client:/app:cached
    working_dir: /app
    ports: 
      - 3000:3000
    command: bash -c "npm install && npm start"

  server:
    image: node:latest
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - 3001:3000
    command: bash -c "npm install && npm start"
    depends_on:
      - mongo
    networks:
      - docker-todo-list

  mongo:
    image: mongo
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017 
    networks:
      - docker-todo-list

networks:
  docker-todo-list:
    driver: bridge
